### ISSUE TITLE
Créer la structure de base de données

### ISSUE THREAD

**Issue by Bunkermaster** [Bunkermaster/KandTG1#2]
Ajouter une table `page` qui contient toutes les données à stocker pour notre page.

Dans phpmyadmin vous allez créer une base utf8mb4_unicode_ci et nous partagerons la définition ensemble.

**Comment by juliemanhes** [comment]
-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Client :  localhost:8889
-- Généré le :  Mar 28 Février 2017 à 16:32
-- Version du serveur :  5.5.42
-- Version de PHP :  7.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `page`
--

-- --------------------------------------------------------

--
-- Structure de la table `page`
--

CREATE TABLE `page` (
  `id` int(11) NOT NULL,
  `h1` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alt` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nav-title` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Contenu de la table `page`
--

INSERT INTO `page` (`id`, `h1`, `description`, `img`, `alt`, `slug`, `nav-title`) VALUES
(1, 'Les Teletubbies', 'C''est flippant.', 'img/teletubbies.jpg', '', '', ''),
(2, 'Les Chatons !', 'C''est mignon.\r\n\r\n', 'img/three_kittens.jpg', '', '', ''),
(3, 'Iron Maiden!', 'C''est vieux.', 'img/ironmaiden.jpg', '', '', ''),
(4, '16 horsepower', 'Woooaaaah', 'img/raf.jpg', '', '', ''),
(5, 'Les mangas!!!', 'Woooooah la culture Japonaise\r\n\r\n', 'img/manga.jpg', '', '', '');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `page`
--
ALTER TABLE `page`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `page`
--
ALTER TABLE `page`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=6;

**Comment by Bunkermaster** [comment]
:+1 wesh @juliemanhes
